- modular_mithra/code/modules/mithra/01_ears.dm
- modular_mithra/code/modules/mithra/07_traits.dm
- modular_mithra/code/modules/mithra/traits.dm
- modular_mithra/code/modules/mithra/traits_negative.dm
Traducciones a algunas traits xd
:cl: Keila
traduction: Archivos de Traits
/:cl:
> Traducciones BoH parte 1

- code/modules/codex/entries/guns.dm
> Traducción codex de las armas

- code/game/jobs/job/civilian.dm
- maps/torch/job/supply_jobs.dm
> Era este xd

- code/modules/codex/entries/guns.dm
- modular_mithra/code/modules/mithra/body_markings.dm
- modular_mithra/code/modules/mithra/traits_neutral.dm
- modular_mithra/code/modules/mithra/traits_positive.dm
Sustituye las tildes de algunas traducciones por las versiones sin tilde, puesto que el código no es capaz de soportarlas.
Cuando se arregle las ñ del dm de los IA, arreglaré el resto de dm que tengan el fallo de la "ñ"
> Arreglo de tildes.

- code/datums/ai_law_sets.dm
> Arreglos en las leyes de IA

- code/datums/ai_law_sets.dm
> leyes de la AI.dm

- code/datums/supplypacks/atmospherics.dm
- code/datums/supplypacks/custodial.dm
- code/datums/supplypacks/emergency.dm
- code/datums/supplypacks/operations.dm
- code/datums/supplypacks/supply.dm
- code/datums/uplink/medical.dm
- code/modules/emotes/definitions/visible.dm
- code/modules/paperwork/pen/multi_pen.dm
traduzco varías cosas como algunos pedidos de cargo y unas acciones.
> No se que título ponerle, solo traduzco poquito.

- maps/torch/job/torch_jobs.dm
¡:D!
NO SEREMOS MÁS ADHERENTFOBOS, NUESTROS QUERIDO NIÑEROS PULPO ROBOTS NOS SERVIRÁN. NUESTROS NUEVOS ESCLAVO-- AMIGOS.
> YA NO SOMOS MÁS ADHERENTFOBOS

- maps/torch/torch1_deck5.dmm
- maps/torch/torch5_deck1.dmm
> Cambios Medbay, by CEO of Medbay

- maps/torch/torch1_deck5.dmm
- maps/torch/torch5_deck1.dmm
Reverts Foxterosa/BoH-Bay#38 Lo siento Alejo, aquí acaba tu rework
> Revert "Cambios Medbay, by CEO of Medbay"

- maps/torch/job/hestia_jobs.dm
Reactiva los jobs de infanteria que se encontraban en 0.
> Camper quiere ser niñero de vuelta.

- maps/torch/torch5_deck1.dmm
Veeerga, me olvide una puerta, jiji
Pero yaaa
> Ultimo arreglito

- maps/torch/structures/closets/supply.dm
- maps/torch/torch1_deck5.dmm
- maps/torch/torch2_deck4.dmm
Cargo esta mas bonito
Y ahora anda el elevador.
> Cargo modificiado y arreglado

- maps/torch/torch1_deck5.dmm
- maps/torch/torch6_bridge.dmm
> Nuevo Garuda

- code/modules/organs/robolimbs.dm
Le permite a las siguientes razas usar extremidades roboticas:
-Veteris unathi
-Vulpakinn
-Akula
-Tarjaran
-Promethean
> Prostetics para casi todos

- maps/torch/torch4_deck2.dmm
- maps/torch/torch5_deck1.dmm
- Corte
- Sala de descanso de Med
- Equipo para locos en el almacen de Med
- Arreglos en suelos de Med
> Corte y agregados menores

- maps/torch/torch5_deck1.dmm
-Sec
-Robotica
-Ciencias
-Otros
> Deck 1 remasterizado

- maps/torch/torch1_deck5.dmm
> Deck 5 remasterizado

- code/modules/boh_misc/munitions.dm
- code/modules/mob/living/simple_animal/hostile/leech.dm
Soluciona el problema del lag causado por 3 sindicalistas intentando matar bichos en x base.
> Adios Lag *No del todo

- maps/torch/items/rewards.dm
- maps/torch/structures/closets/medical.dm
- maps/torch/torch2_deck4.dmm
- maps/torch/torch5_deck1.dmm
- maps/torch/torch6_bridge.dmm
-La silla del CO
-Esto
-Un suelito en Med que faltaba
-Medallas basicas en Bridge para los Heads
> Arreglitos x2

- maps/torch/torch2_deck4.dmm
- maps/torch/torch3_deck3.dmm
- maps/torch/torch5_deck1.dmm
- maps/torch/torch6_bridge.dmm
> Revert "Saferroms"

- maps/torch/infantry/storage.dm
- maps/torch/infantry/vending.dm
- maps/torch/structures/closets.dm
- maps/torch/torch1_deck5.dmm
-Agrega una radio, mascara y prybar a los lockers de los soldados.
-Elimina la caja de kits de los Rifleman (tienen armas grandes en su armeria y pistolas en su locker)
-Cambia la caja de Combat technicia (solo tiene equipo de med: stabilization kit, stasis bag y cinturon medico. Las armas grandes en la armeria y pistola en su locker, como los rifleman)
Ademas agrega un cinturon con herramientas y una multitool a su locker
-Cambio en la cantidad de municion de su vendor
-Cambios en la armeria: 2 bullpup, 2 carabinas laser y 1 lanzagranadas
> Infanteria

- code/game/objects/items/devices/scanners/health.dm
Pueeees, traduje el "Analizador de salud"
> Health Analyzer tradu

- maps/torch/structures/closets/medical.dm
- maps/torch/torch6_bridge.dmm
-Oficina del CMO
-Oficina del CoS
-Oficina del CSO
-Oficina del CE
-Bridge
> Bridge, cambios

- code/_helpers/medical_scans.dm
- code/game/objects/items/devices/scanners/health.dm
> Tradus para meds

- code/modules/interactions/lewd/_lewd.dm
- code/modules/species/species.dm
- code/modules/species/station/adherent.dm
- code/modules/species/station/lizard_subspecies.dm
- code/modules/species/station/station.dm
Ahora aparece "groin" en vez de BP_GROIN
> arregla un pequeño error en el sitema de erp

- code/game/machinery/bioprinter.dm
- code/game/machinery/bodyscanner.dm
- code/game/machinery/bodyscanner_console.dm
- code/game/machinery/bodyscanner_display.dm
- code/game/objects/items/bodybag.dm
- code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
- code/modules/modular_computers/hardware/scanners/scanner_medical.dm
> Tradus para Med

- maps/torch/torch6_bridge.dmm
> Se me olvido

- code/_helpers/medical_scans.dm
- code/game/objects/items/weapons/autopsy.dm
- code/modules/organs/internal/_internal.dm
- Arreglo de algunos errores en palabras y su orden
- Tambien se tradujo las autopsias
> Fix y autopsias
